###
# create a game
POST http://localhost:8000/games
Content-Type: application/json

{
    "name": "my_game_name",
    "password": "secret",
    "maze_id": "maze_id1"
}

###
# get all games
GET http://localhost:8000/games
Content-Type: application/json

{
}
###
# get one game
GET http://localhost:8000/games/bee7e9d9-0ea8-4c2a-9859-55b510aa9735
Content-Type: application/json

{
}

###
# get all mazes
GET http://localhost:8000/mazes
Content-Type: application/json

{
}

###
# get one maze
GET http://localhost:8000/mazes/maze_id1
Content-Type: application/json

{
}
