###############################################################
# Mazes
###############################################################
###
# get all mazes
GET http://localhost:8000/mazes
Content-Type: application/json

{
}

###
# get one maze
GET http://localhost:8000/mazes/maze_id1
Content-Type: application/json

{
}
###############################################################
# Games
###############################################################
###
# create a game
POST http://localhost:8000/games
Content-Type: application/json

{
    "umpire_id": "12345",
    "game_name": "my_game_name",
    "game_password": "secret",
    "maze_id": "maze_id1"
}

###
# get all games
GET http://localhost:8000/games
Content-Type: application/json

{
}
###
# get info about a/one game
GET http://localhost:8000/games/cc79dfcf-9d53-4afd-aabe-ff5e08512dd7
Content-Type: application/json

{
}
###############################################################
# Register
###############################################################
###
# Modify a game, in this case register a user
PUT http://localhost:8000/games/8fab52af-8bf6-425f-9227-185fbfad11ca
Content-Type: application/json

{
  "player_name": "jan",
  "player_id": "eikel",
  "password": "secret"
}
